# Generated by Django 5.1 on 2024-08-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titre')),
                ('sumary', models.CharField(max_length=50, verbose_name='Sommaire')),
                ('content', models.TextField(verbose_name='contenu')),
                ('date_pub', models.DateField(null=True, verbose_name='Date de publication')),
            ],
        ),
    ]
