# Generated by Django 5.1 on 2024-08-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=2, max_length=50, upload_to='images', verbose_name='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='sumary',
            field=models.CharField(max_length=50, null=True, verbose_name='Sommaire'),
        ),
    ]
